site_name: RISC-V for BLDC control
repo_name: 24b-cti-riscv
repo_url: https://github.com/pfeinsper/24b-cti-riscv.git
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate  # Dark mode as the default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: yellow
      accent: orange
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: yellow
      accent: orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Hardware: getting-started/hardware.md
    - Software: getting-started/software.md
    - Development: getting-started/development.md