name: Quartus CI/CD Pipeline

on:
  push:
    paths:
      - '/de0-nano-sdram-qsys/hw**'  # Substitua pelo caminho da pasta que você quer monitorar
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  quartus:
    name: Quartus Build and Test
    runs-on: ubuntu-latest
    container:
      image: rodrigoanciaes/cti-24b:v1
      options: --entrypoint /bin/bash -v ${{ github.workspace }}:/root/workspace
    env:
      PYTHONPATH: "/root/workspace/"
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Executar Compilação com Quartus
        run: |
          quartus_sh --flow compile /root/workspace/de0-nano-sdram-qsys/hw/de0-neorv32-sdram-qsys.qpf

      - name: Verificar criação do arquivo .sof
        run: |
          if [ -f "/root/workspace/de0-nano-sdram-qsys/hw/output_files/de0-neorv32-sdram-qsys.sof" ]; then
            echo "Compilação bem-sucedida."
          else
            echo "Erro na compilação."
            exit 1
          fi
