name: Quartus CI/CD Pipeline

on:
  push:
    paths:
      - '/de0-nano-sdram-qsys/hw/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  quartus:
    name: Quartus Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Excluir pasta /opt/hostedtoolcache para liberar espaço em disco
        run: sudo rm -rf /opt/hostedtoolcache

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Construir a Imagem Docker para o CI/CD
        run: |
          docker build -t quartus-image-ci:latest -f .devcontainer/Dockerfile .

      - name: Executar Compilação com Quartus
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/root/workspace \
            -e PYTHONPATH="/root/workspace/" \
            quartus-image-ci:latest \
            quartus_sh --flow compile /root/workspace/de0-nano-sdram-qsys/hw/de0-neorv32-sdram-qsys.qpf

      - name: Verificar criação do arquivo .sof
        run: |
          if [ -f "${{ github.workspace }}/de0-nano-sdram-qsys/hw/output_files/de0-neorv32-sdram-qsys.sof" ]; then
            echo "Compilação bem-sucedida."
          else
            echo "Erro na compilação."
            exit 1
          fi
